-- MySQL Script generated by MySQL Workbench
-- Sun May 16 13:32:54 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema projetoSAE
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetoSAE
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetoSAE` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `projetoSAE` ;

-- -----------------------------------------------------
-- Table `projetoSAE`.`SAE_CategoriasListaOpcoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoSAE`.`SAE_CategoriasListaOpcoes` ;

CREATE TABLE IF NOT EXISTS `projetoSAE`.`SAE_CategoriasListaOpcoes` (
  `codCategoriasListaOpcoes` INT NOT NULL AUTO_INCREMENT,
  `descricaoCategoriasOpcoes` VARCHAR(150) NOT NULL,
  `nomeInternoCategoriasOpcoes` VARCHAR(150) NULL,
  `ordemCategoriasOpcoes` INT NULL,
  PRIMARY KEY (`codCategoriasListaOpcoes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE UNIQUE INDEX `ordemCategoria_UNIQUE` ON `projetoSAE`.`SAE_CategoriasListaOpcoes` (`ordemCategoriasOpcoes` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projetoSAE`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoSAE`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `projetoSAE`.`Cliente` (
  `codCliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(150) NOT NULL,
  `telefone` VARCHAR(20) NULL,
  PRIMARY KEY (`codCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetoSAE`.`TipoProduto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoSAE`.`TipoProduto` ;

CREATE TABLE IF NOT EXISTS `projetoSAE`.`TipoProduto` (
  `codTipoProduto` INT NOT NULL AUTO_INCREMENT,
  `descricaoTipo` VARCHAR(120) NOT NULL,
  PRIMARY KEY (`codTipoProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projetoSAE`.`Produtos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoSAE`.`Produtos` ;

CREATE TABLE IF NOT EXISTS `projetoSAE`.`Produtos` (
  `codProdutos` INT NOT NULL AUTO_INCREMENT,
  `descricaoProduto` VARCHAR(120) NOT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  `codTipoProduto` INT NOT NULL,
  `statusAtivo` BIT(1) NOT NULL,
  PRIMARY KEY (`codProdutos`),
  CONSTRAINT `fk_Produtos_TipoProduto1`
    FOREIGN KEY (`codTipoProduto`)
    REFERENCES `projetoSAE`.`TipoProduto` (`codTipoProduto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Produtos_TipoProduto1_idx` ON `projetoSAE`.`Produtos` (`codTipoProduto` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projetoSAE`.`Cargos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoSAE`.`Cargos` ;

CREATE TABLE IF NOT EXISTS `projetoSAE`.`Cargos` (
  `codCargos` INT NOT NULL AUTO_INCREMENT,
  `descricaoCargos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codCargos`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetoSAE`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoSAE`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `projetoSAE`.`Usuario` (
  `codUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(120) NOT NULL,
  `login` VARCHAR(120) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `codCargos` INT NOT NULL,
  PRIMARY KEY (`codUsuario`),
  CONSTRAINT `fk_Usuario_Cargos1`
    FOREIGN KEY (`codCargos`)
    REFERENCES `projetoSAE`.`Cargos` (`codCargos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_Usuario_Cargos1_idx` ON `projetoSAE`.`Usuario` (`codCargos` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projetoSAE`.`StatusPedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoSAE`.`StatusPedido` ;

CREATE TABLE IF NOT EXISTS `projetoSAE`.`StatusPedido` (
  `codStatusPedido` INT NOT NULL AUTO_INCREMENT,
  `statusDescricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codStatusPedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetoSAE`.`Pedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoSAE`.`Pedido` ;

CREATE TABLE IF NOT EXISTS `projetoSAE`.`Pedido` (
  `codPedido` INT NOT NULL AUTO_INCREMENT,
  `codStatusPedido` INT NOT NULL,
  `codCliente` INT NOT NULL,
  `codUsuarioRegistro` INT NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `valorPedido` DECIMAL(10,2) NOT NULL,
  `codUsuarioEntrega` INT NULL,
  `dataEntrega` DATETIME NULL,
  `codUsuarioExclusao` INT NULL,
  `dataExclusao` DATETIME NULL,
  PRIMARY KEY (`codPedido`),
  CONSTRAINT `fk_Pedido_StatusPedido1`
    FOREIGN KEY (`codStatusPedido`)
    REFERENCES `projetoSAE`.`StatusPedido` (`codStatusPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Cliente`
    FOREIGN KEY (`codCliente`)
    REFERENCES `projetoSAE`.`Cliente` (`codCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pedido_Usuario`
    FOREIGN KEY (`codUsuarioRegistro`)
    REFERENCES `projetoSAE`.`Usuario` (`codUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_Pedido_StatusPedido_idx` ON `projetoSAE`.`Pedido` (`codStatusPedido` ASC) INVISIBLE;

CREATE INDEX `fk_Pedido_Cliente_idx` ON `projetoSAE`.`Pedido` (`codCliente` ASC) VISIBLE;

CREATE INDEX `fk_Pedido_Usuario_idx` ON `projetoSAE`.`Pedido` (`codUsuarioRegistro` ASC) INVISIBLE;


-- -----------------------------------------------------
-- Table `projetoSAE`.`ItensPedido`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoSAE`.`ItensPedido` ;

CREATE TABLE IF NOT EXISTS `projetoSAE`.`ItensPedido` (
  `codPedido` INT NOT NULL,
  `codProdutos` INT NOT NULL,
  `quatidade` INT NOT NULL,
  `valosFinal` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`codPedido`, `codProdutos`),
  CONSTRAINT `fk_ItensPedido_Pedido1`
    FOREIGN KEY (`codPedido`)
    REFERENCES `projetoSAE`.`Pedido` (`codPedido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ItensPedido_Produtos1`
    FOREIGN KEY (`codProdutos`)
    REFERENCES `projetoSAE`.`Produtos` (`codProdutos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_Pedido_has_Produtos_Produtos1_idx` ON `projetoSAE`.`ItensPedido` (`codProdutos` ASC) VISIBLE;

CREATE INDEX `fk_Pedido_has_Produtos_Pedido1_idx` ON `projetoSAE`.`ItensPedido` (`codPedido` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projetoSAE`.`SAE_CategoriasItens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoSAE`.`SAE_CategoriasItens` ;

CREATE TABLE IF NOT EXISTS `projetoSAE`.`SAE_CategoriasItens` (
  `codCategoriasItens` INT NOT NULL AUTO_INCREMENT,
  `descricaoCategorias` VARCHAR(150) NOT NULL,
  `nomeInternoCategorias` VARCHAR(150) NULL,
  `ordemCategoria` INT NULL,
  PRIMARY KEY (`codCategoriasItens`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE UNIQUE INDEX `ordemCategoria_UNIQUE` ON `projetoSAE`.`SAE_CategoriasItens` (`ordemCategoria` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projetoSAE`.`SAE_ItensFormularios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoSAE`.`SAE_ItensFormularios` ;

CREATE TABLE IF NOT EXISTS `projetoSAE`.`SAE_ItensFormularios` (
  `codItensFormularios` INT NOT NULL AUTO_INCREMENT,
  `descricaoItem` VARCHAR(500) NOT NULL,
  `ordemItem` INT NULL,
  `codCategoriasItens` INT NULL,
  `opcoesItensJSON` JSON NULL,
  PRIMARY KEY (`codItensFormularios`),
  CONSTRAINT `fk_codCategorias_Itens`
    FOREIGN KEY (`codCategoriasItens`)
    REFERENCES `projetoSAE`.`SAE_CategoriasItens` (`codCategoriasItens`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE UNIQUE INDEX `ordemCategoria_UNIQUE` ON `projetoSAE`.`SAE_ItensFormularios` (`ordemItem` ASC) VISIBLE;

CREATE INDEX `fk_codCategorias_Itens_idx` ON `projetoSAE`.`SAE_ItensFormularios` (`codCategoriasItens` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `projetoSAE`.`SAE_ItensOpcoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `projetoSAE`.`SAE_ItensOpcoes` ;

CREATE TABLE IF NOT EXISTS `projetoSAE`.`SAE_ItensOpcoes` (
  `codItensOpcoes` INT NOT NULL AUTO_INCREMENT,
  `descricaoOpcoes` VARCHAR(500) NOT NULL,
  `ordemOpcoes` INT NULL,
  `codCategoriasListaOpcoes` INT NULL,
  `opcoesItensJSON` JSON NULL,
  PRIMARY KEY (`codItensOpcoes`),
  CONSTRAINT `fk_codCategorias_ListaOpcoes`
    FOREIGN KEY (`codCategoriasListaOpcoes`)
    REFERENCES `projetoSAE`.`SAE_CategoriasListaOpcoes` (`codCategoriasListaOpcoes`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE UNIQUE INDEX `ordemCategoria_UNIQUE` ON `projetoSAE`.`SAE_ItensOpcoes` (`ordemOpcoes` ASC) VISIBLE;

CREATE INDEX `fk_codCategorias_ListaOpcoes_idx` ON `projetoSAE`.`SAE_ItensOpcoes` (`codCategoriasListaOpcoes` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
