-- MySQL Script generated by MySQL Workbench
-- Thu May 12 00:15:58 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema projetosae
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projetosae
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projetosae` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `projetosae` ;

-- -----------------------------------------------------
-- Table `projetosae`.`enf_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetosae`.`enf_usuario` (
  `codUsuarioUUId` VARCHAR(45) NOT NULL,
  `nomeUsuario` VARCHAR(100) NOT NULL,
  `nomePessoa` VARCHAR(250) NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `dataCadastro` DATETIME NOT NULL,
  `dataExclusao` DATETIME NULL,
  PRIMARY KEY (`codUsuarioUUId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `projetosae`.`enf_prontuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetosae`.`enf_prontuario` (
  `codProntuarioUUId` VARCHAR(45) NOT NULL,
  `codUsuarioUUId` VARCHAR(45) NOT NULL,
  `nomePaciente` VARCHAR(250) NOT NULL,
  `dataNascimento` DATETIME NOT NULL,
  `altura` FLOAT NULL,
  `peso` FLOAT NULL,
  `imc` FLOAT NULL,
  `glicemia` FLOAT NULL,
  `pressaoArterial` FLOAT NULL,
  `oximetria` FLOAT NULL,
  `dataCriacao` DATETIME NOT NULL,
  `dataAlteracao` DATETIME NULL,
  `dataExclusao` DATETIME NULL,
  PRIMARY KEY (`codProntuarioUUId`),
  CONSTRAINT `fk_codUsuarioProntuarioUUId`
    FOREIGN KEY (`codUsuarioUUId`)
    REFERENCES `projetosae`.`enf_usuario` (`codUsuarioUUId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_codUsuarioProntuarioUUId_idx` ON `projetosae`.`enf_prontuario` (`codUsuarioUUId` ASC) ;


-- -----------------------------------------------------
-- Table `projetosae`.`enf_anamnesediagnostico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetosae`.`enf_anamnesediagnostico` (
  `codAnamneseDiagnosticoUUId` VARCHAR(45) NOT NULL,
  `codProntuarioUUId` VARCHAR(45) NOT NULL,
  `diagnosticosJSON` JSON NULL,
  `intervencoesJSON` JSON NULL,
  `resultadosJSON` JSON NULL,
  `dataCriacao` DATETIME NOT NULL,
  PRIMARY KEY (`codAnamneseDiagnosticoUUId`),
  CONSTRAINT `fk_codProntuarioAnamneseUUId`
    FOREIGN KEY (`codProntuarioUUId`)
    REFERENCES `projetosae`.`enf_prontuario` (`codProntuarioUUId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_codProntuarioAnamneseUUId_idx` ON `projetosae`.`enf_anamnesediagnostico` (`codProntuarioUUId` ASC) ;


-- -----------------------------------------------------
-- Table `projetosae`.`enf_comentarioprontuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetosae`.`enf_comentarioprontuario` (
  `codComentarioProntuarioUUId` VARCHAR(45) NOT NULL,
  `codProntuarioUUId` VARCHAR(45) NOT NULL,
  `codUsuarioUUId` VARCHAR(45) NOT NULL,
  `comentarioProntuario` VARCHAR(1000) NULL,
  `dataCriacao` DATETIME NOT NULL,
  PRIMARY KEY (`codComentarioProntuarioUUId`),
  CONSTRAINT `fk_codProntuarioComentarioUUId`
    FOREIGN KEY (`codProntuarioUUId`)
    REFERENCES `projetosae`.`enf_prontuario` (`codProntuarioUUId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codUsuarioComentarioUUId`
    FOREIGN KEY (`codUsuarioUUId`)
    REFERENCES `projetosae`.`enf_usuario` (`codUsuarioUUId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_codProntuarioComentarioUUId_idx` ON `projetosae`.`enf_comentarioprontuario` (`codProntuarioUUId` ASC) ;

CREATE INDEX `fk_codUsuarioComentarioUUId_idx` ON `projetosae`.`enf_comentarioprontuario` (`codUsuarioUUId` ASC) ;


-- -----------------------------------------------------
-- Table `projetosae`.`enf_notificacaousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetosae`.`enf_notificacaousuario` (
  `codNotificacaoUsuarioUUId` VARCHAR(45) NOT NULL,
  `codUsuarioUUId` VARCHAR(45) NOT NULL,
  `codComentarioProntuarioUUId` VARCHAR(45) NOT NULL,
  `usuarioAlvo` VARCHAR(45) NOT NULL,
  `notificacaoVista` VARCHAR(5) NOT NULL,
  `dataCriacao` DATETIME NOT NULL,
  PRIMARY KEY (`codNotificacaoUsuarioUUId`),
  CONSTRAINT `fk_codComentarioProntuarioNotificacaoUUId`
    FOREIGN KEY (`codComentarioProntuarioUUId`)
    REFERENCES `projetosae`.`enf_comentarioprontuario` (`codComentarioProntuarioUUId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codUsuarioNotificacaoUUId`
    FOREIGN KEY (`codUsuarioUUId`)
    REFERENCES `projetosae`.`enf_usuario` (`codUsuarioUUId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_codUsuarioNotificacaoUUId_idx` ON `projetosae`.`enf_notificacaousuario` (`codUsuarioUUId` ASC) ;

CREATE INDEX `fk_codComentarioProntuarioNotificacaoUUId_idx` ON `projetosae`.`enf_notificacaousuario` (`codComentarioProntuarioUUId` ASC) ;


-- -----------------------------------------------------
-- Table `projetosae`.`enf_rascunhoprontuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetosae`.`enf_rascunhoprontuario` (
  `codRascunhoProntuarioUUId` VARCHAR(45) NOT NULL,
  `codProntuarioUUId` VARCHAR(45) NOT NULL,
  `codUsuarioUUId` VARCHAR(45) NOT NULL,
  `formKeysRascunhoJSON` JSON NULL,
  `dataCriacao` DATETIME NOT NULL,
  PRIMARY KEY (`codRascunhoProntuarioUUId`),
  CONSTRAINT `fk_codProntuarioRascunhoUUId`
    FOREIGN KEY (`codProntuarioUUId`)
    REFERENCES `projetosae`.`enf_prontuario` (`codProntuarioUUId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codUsuarioRascunhoUUId`
    FOREIGN KEY (`codUsuarioUUId`)
    REFERENCES `projetosae`.`enf_usuario` (`codUsuarioUUId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_codUsuarioRascunhoUUId_idx` ON `projetosae`.`enf_rascunhoprontuario` (`codUsuarioUUId` ASC) ;

CREATE INDEX `fk_codProntuarioRascunhoUUId_idx` ON `projetosae`.`enf_rascunhoprontuario` (`codProntuarioUUId` ASC) ;


-- -----------------------------------------------------
-- Table `projetosae`.`sae_categoriasitens`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetosae`.`sae_categoriasitens` (
  `codCategoriasItensUUId` VARCHAR(45) NOT NULL,
  `descricaoCategoriasItens` VARCHAR(200) NOT NULL,
  `nomeInternoCategoriasItens` VARCHAR(200) NULL DEFAULT NULL,
  `ordemCategoriaItens` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codCategoriasItensUUId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE UNIQUE INDEX `ordemCategoriaItens_UNIQUE` ON `projetosae`.`sae_categoriasitens` (`ordemCategoriaItens` ASC) ;


-- -----------------------------------------------------
-- Table `projetosae`.`sae_categoriaslistaopcoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetosae`.`sae_categoriaslistaopcoes` (
  `codCategoriasListaOpcoesUUId` VARCHAR(45) NOT NULL,
  `descricaoCategoriasOpcoes` VARCHAR(200) NOT NULL,
  `nomeInternoCategoriasOpcoes` VARCHAR(200) NULL DEFAULT NULL,
  `ordemCategoriasOpcoes` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`codCategoriasListaOpcoesUUId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE UNIQUE INDEX `ordemCategoriasOpcoes_UNIQUE` ON `projetosae`.`sae_categoriaslistaopcoes` (`ordemCategoriasOpcoes` ASC) ;


-- -----------------------------------------------------
-- Table `projetosae`.`sae_itensformularios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetosae`.`sae_itensformularios` (
  `codItensFormularios` INT(11) NOT NULL AUTO_INCREMENT,
  `descricaoItem` VARCHAR(500) NOT NULL,
  `ordemItem` INT(11) NULL DEFAULT NULL,
  `codCategoriasItensUUId` VARCHAR(45) NOT NULL,
  `codCategoriasListaOpcoesUUId` VARCHAR(45) NULL DEFAULT NULL,
  `opcoesItensFormJSON` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`codItensFormularios`),
  CONSTRAINT `fk_codCategoriasItensUUIdIDX`
    FOREIGN KEY (`codCategoriasItensUUId`)
    REFERENCES `projetosae`.`sae_categoriasitens` (`codCategoriasItensUUId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_codCategoriasListaOpcoesUUIdIDX`
    FOREIGN KEY (`codCategoriasListaOpcoesUUId`)
    REFERENCES `projetosae`.`sae_categoriaslistaopcoes` (`codCategoriasListaOpcoesUUId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 133
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_codCategoriasItensUUIdIDX` ON `projetosae`.`sae_itensformularios` (`codCategoriasItensUUId` ASC) ;

CREATE INDEX `fk_codCategoriasListaOpcoesUUIdIDX` ON `projetosae`.`sae_itensformularios` (`codCategoriasListaOpcoesUUId` ASC) ;


-- -----------------------------------------------------
-- Table `projetosae`.`sae_itensopcoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projetosae`.`sae_itensopcoes` (
  `codItensOpcoes` INT(11) NOT NULL AUTO_INCREMENT,
  `descricaoOpcoes` VARCHAR(500) NOT NULL,
  `ordemOpcoes` INT(11) NULL DEFAULT NULL,
  `codCategoriasListaOpcoesUUId` VARCHAR(45) NOT NULL,
  `listaOpcoesJSON` JSON NULL DEFAULT NULL,
  PRIMARY KEY (`codItensOpcoes`),
  CONSTRAINT `fk_codCategoriasListaOpcoesUUId`
    FOREIGN KEY (`codCategoriasListaOpcoesUUId`)
    REFERENCES `projetosae`.`sae_categoriaslistaopcoes` (`codCategoriasListaOpcoesUUId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;

CREATE INDEX `fk_codCategoriasListaOpcoesUUId` ON `projetosae`.`sae_itensopcoes` (`codCategoriasListaOpcoesUUId` ASC) ;



-- -----------------------------------------------------
-- Table `projetosae`.`enf_numeroprontuario`
-- -----------------------------------------------------

CREATE TABLE IF NOT EXISTS `projetosae`.`enf_numeroprontuario` (
  `numeroprontuario` INT NOT NULL AUTO_INCREMENT,
  `codProntuarioUUId` VARCHAR(45) NULL,
  PRIMARY KEY (`numeroprontuario`),
  INDEX `fk_codProntuarioNumeroUUId_idx` (`codProntuarioUUId` ASC),
  CONSTRAINT `fk_codProntuarioUUId`
    FOREIGN KEY (`codProntuarioUUId`)
    REFERENCES `projetosae`.`enf_prontuario` (`codProntuarioUUId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 100


enf_comentarioprontuarioenf_comentarioprontuarioenf_comentarioprontuarioSET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
